#In the config, the things that should be changed should overall be the compatibility and options if you're using a Practice Plugin and want Bot-Practice to be compatible with it.

settings:
  Bots: true
   Debug: false # Experimental / Developers Only
  
compatibility: #for other plugins you want to use with Bot Practice (VERY COMPATIBLE)
  StrikePractice: false #this is not a practice plugin you'd want to use with Bot Practice
  Frost: false
  Yang-Practice: false
  Array-Practice: false
  mPractice: false
  Proxial-Practice: false
  IcePractice: false
  nPractice: false
  cPractice: false
  hPractice: false
  Praxi: false
  Cold-Practice: false #Not sure if this will work, just praying that it will, doubt anyone would use it though
  PotPvP: false #Should work with mostly every fork
  #if you have anymore plugins, please suggest them @ tdvne#0001 or https://discord.esta.land

# Custom Artificial Intelligence Learning
# Orginially created by tdvne & further improved by Aurora

Main-AI:
 Pathfinding-Main-Algorithm: A* #DO NOT CHANGE
 Auto-Learn: true
   Data-Collected: # Experimental
    Running: true
    Strafing: true
    Pearling: true
    Per-Block: false
    Combolock: true
 
Secondary-AI:
 Auto-update: true

Developer-API:
 Github: '' #Still working in progress 
