MONGODB:
  ADDRESS: "127.0.0.1"
  PORT: 27017
  DATABASE: "botpractice"
  AUTHENTICATION:
    ENABLED: false
    DATABASE: "admin"
    USERNAME: ""
    PASSWORD: ""

# I don't know

MONGO-URI:
DATABASE:
